### ISSUE TITLE
A minor mistake of duplicate description

### ISSUE THREAD

**Issue by William-PanWei** [ietf-rats-wg/basic-yang-module#1]
The description of COSE_Algorithm-value
https://github.com/ietf-rats-wg/basic-yang-module/blob/da656b35802d86fcf2caad972b23de5c9cf59986/ietf-tpm-remote-attestation.yang#L247
is the same as that of TPM_ALG_ID-value.
https://github.com/ietf-rats-wg/basic-yang-module/blob/da656b35802d86fcf2caad972b23de5c9cf59986/ietf-tpm-remote-attestation.yang#L236

**Comment by henkbirkholz** [comment]
Thanks! Fixed in commit https://github.com/ietf-rats-wg/basic-yang-module/commit/b0c9e94f32f7304cc8cb1565e00aabba754e7d70.
