### ISSUE TITLE
TCG algorithms in YANG model

### ISSUE THREAD

**Issue by ericvoit** [ietf-rats-wg/basic-yang-module#10]
During the charra presentation at IETF 108, we said we were going to ask the following question to the list: "Should the algorithm set defined in YANG be reduced to just those asymmetric algorithms currently exposed in the current TPM 1.2 and 2 specifications?"

This is reflected seen in https://www.ietf.org/proceedings/108/slides/slides-108-rats-sessb-charra-update-00, Slide 7.

The proposal I would like to make is as follows:

The TCG tracked algorithms supportable by a TPM should be the only ones included in a charra maintained list of YANG identities.   

- This identity set needs to be extendable to new algorithms for any YANG models which augment charra.

TCG Algorithm Registry Revision 01.32, Table 3 at https://trustedcomputinggroup.org/wp-content/uploads/TCG-_Algorithm_Registry_r1p32_pub.pdf contains the algorithms we should encode.

- There are other types of information within this table, and we might as well encode the full table within a YANG model.   That way we can explicitly make the scope of a "ietf-tcg-algs.yang" model the contents this TCG table encoded in YANG.

- The YANG model will indicate what TCG algorithms are deprecated by the IETF.  However identities for these deprecated algorithms from the TCG table will be assigned.  (e.g., SHA-1)

**Comment by henkbirkholz** [comment]
This issue has been addressed by the addition of ietf-tcg-algs.yang
Other types of information are covered by the corresponding identity taxonomy introduced.
Alg deprecation should be discussed on list, maybe during YANG doc review
